### ISSUE TITLE
Support for multipart form file uploads?

### ISSUE THREAD

**Issue by mikeharty** [gmac/graphql-stitching-ruby#101]
I recently added support for multipart form file uploads in the project where I've implemented this library. I've been debating whether or not it's something that would make sense to incorporate here.

My implementation has deviated pretty far in this particular area; I implemented a custom `HttpExecutable` in order to swap the client to `RestClient` (needed a proxy), and to add pre/post-request hook points to manipulate queries and responses. This is also where the multipart form handling happens, I'm using [apollo_upload_server-ruby](https://github.com/jetruby/apollo_upload_server-ruby), which does follow the [spec](https://github.com/jaydenseric/graphql-multipart-request-spec), but is a Rails specific implementation.

I say all of that essentially to say, maybe that's where this belongs, in a custom implementation, if needed. I figured I'd get your take before making that assumption. The thought also crossed my mind that maybe there's a plugin-style approach that would make sense. Let me know if there's any interest here, I'm happy to more formally propose a solution if there's an appetite for it, just wanted to gauge whether this feels messy/out of scope first.

**Comment by gmac** [comment]
Let's collaborate on it. I've only used multipart forms a little bit with GraphQL. Sounds like you've hacked together a working solution around stitching? Cleanup/isolate your work as much as you can on a branch and send it over. I'd be happy to look through what you've done and consider what degree we could formally integrate it into the core stitching library. It's a useful feature to support.

**Comment by gmac** [comment]
Scanning quickly through the spec again, I think plug-in is probably the most likely support path, probably with at least Rails and maybe also apollo_upload_server as dependencies. Seems likely you’re already using that stack when adding this feature.

**Comment by mikeharty** [comment]
Yep, I'm using RoR and the `apollo_upload_server` gem. The `apollo_upload_server` is essentially Rails middleware that maps file uploads onto the variables object before it reaches the stitching GraphQL client. That part is pretty intuitive and clean, the files can be referenced right from the variables. The catch is that when we want to pass the query off to a subgraph, it needs to be de-mapped back to the multipart request spec so that the next server can handle the upload and mapping.

I think that interface is good, regardless of what framework you're working within, just attach the files directly to the variables object being passed to the stitching GraphQL client. The only thing we'd need to be aware of is what scalar type(s) are associated with files, so that we can look for those and do the de-mapping before making subgraph requests.

I'm out of time for today, but I will follow up with more in the next day or so. In the meantime, I shared my [customized HttpExecutable](https://gist.github.com/mikeharty/2fe77c8d014e588fecf8026b8db3bd76) if you'd like to see what it looks like, the de-mapping method is at 102. Also, it is hard-coded to use a known variable, we'd want to look for the configured scalar like I mentioned.

**Comment by gmac** [comment]
Went through it all and I think I see what you’re saying. This might make sense as a feature of Supergraph or a base utility for executables. If we know the names of upload scalars, then we can:

1. check to see if a location implements an upload type — if not, no transformations necessary.
2. If so, check if the location executes remotely. If not, no transformation necessary.
3. If remote, then run through user-submitted variable definitions/input. Upload types reverse-map. InputObjects types traverse recursively in search of upload types.

This seems workable. Now the question is just how to arrange it all. Makes the most sense in the executable where we know about local vs. remote execution, though it needs Supergraph/Schema and Request for following variable definitions (which executables don’t currently have).

**Comment by mikeharty** [comment]
That sounds pretty close to what I was thinking. I've had a visitor so just getting caught up - I'll put together a proposal that we can review in the next day or two.

**Comment by gmac** [comment]
Have a look at https://github.com/gmac/graphql-stitching-ruby/pull/103, which I _think_ does the raw job of reversing out a files mapping and nulling out file variable values. Double-check my spec formatting :D

**Comment by gmac** [comment]
I think I've got a plan for setting this up... Note the upcoming change in https://github.com/gmac/graphql-stitching-ruby/pull/107 where the Executable `context` argument will be replaced by the `request` object (which contains a reference to context). @mikeharty, you'll need to update your executor accordingly in v1.2.0.

BUT – once executables have the request, and a request has supergraph info... then executables will be able to do things like reverse-map out upload references 😎

**Comment by gmac** [comment]
This has been completed and merged into the v1.2.0 branch (https://github.com/gmac/graphql-stitching-ruby/pull/108 – which is still getting some finishing touches). You can review the final feature code in https://github.com/gmac/graphql-stitching-ruby/pull/103. Once that's out, you should be able to use `HttpExecutable` as a base class and leverage `extract_multipart_form` in your own implementation.
