### ISSUE TITLE
Remote errors are not properly propagated to clients

### ISSUE THREAD

**Issue by shyouhei** [gmac/graphql-stitching-ruby#117]
Hello again.

When one of our location returns an error, GraphQL::Stitching::Client doesn't propagate that error and raises ``undefined local variable or method `index' ``  instead at this line:

https://github.com/gmac/graphql-stitching-ruby/blob/8a859576261accfa469ac6f1f64156a3d6a06b5d/lib/graphql/stitching/executor/boundary_source.rb#L186

Indeed there is no such thing like `index` at this point.

**Comment by gmac** [comment]
Hello, thanks for the report. Good catch, looks like the contents of that block are copy & paste, and clearly aren’t covered by tests. Mind posting the structure of your subgraph error, specifically its path?

**Comment by shyouhei** [comment]
Sorry, we missed the log.  Will include in a report if something else happens.  Thank you for a quick fix!

**Comment by gmac** [comment]
No prob! It was good to noodle with it to find the gaps in test coverage.
