### ISSUE TITLE
Issue mapping Enum values to keys in Composer.build_enum_type

### ISSUE THREAD

**Issue by mikeharty** [gmac/graphql-stitching-ruby#80]
Hello,

First, thanks for writing this, the implementation is very clean and easy to walk through.

I have a case where I'm upgrading a pretty stale version of GraphQL and I've run into an issue with Enums. The project makes use of the `value` property on Enums to translate between GraphQL Enum "labels" and Ruby values, e.g.:

`Enum.value('UNSPECIFIED', 'Unspecified value', value: 'none')` will be `UNSPECIFIED` in the Schema, but if passed as a query argument, will appear as `"none"` in Ruby.

The issue comes up during introspection, when `Composer.build_enum_type` attempts to build the enum types. 

On this line: https://github.com/gmac/graphql-stitching-ruby/blob/main/lib/graphql/stitching/composer.rb#L238 
it is constructing a new `EnumValue` via `EnumValue.value`, but it passes the `value` as the first argument, rather than the `graphql_name`. 

In my case, this causes two issues: 
1. Some of my Enum values are not valid EnumValue names, they are Ruby primitives or don't meet the naming validation rules
2. Those that do pass validation are still detached from their original EnumValue which links the name and value together.

I experimented pretty thoroughly with different approaches to solve this, I was hoping I could achieve it by implementing a custom `enum_value_class`, but the necessary values aren't passed down. For now, I've resorted to monkey-patching `build_enum_type`, which gets the job done for my narrow case, but there's likely a better general solution. For my Schema, I don't have overlapping types, so I can reliably pick the first location an EnumValue was seen and pull the graphql_name off of that, which I've done by simply:

```ruby
enum_values_by_value_location.each do |value, enum_values_by_location|
  # Getting the first location
  location = enum_values_by_location.keys.first
  # Getting the GraphQL name off of it, or falling back to original behavior
  graphql_name = enum_values_by_location[location]&.graphql_name || value
  enum_value = value(graphql_name,
               value: value,
               description: builder.merge_descriptions(type_name, enum_values_by_location, enum_value: value),
               deprecation_reason: builder.merge_deprecations(type_name, enum_values_by_location, enum_value: value))
```

Any tips or thoughts appreciated, happy to offer any addition info as needed.

**Comment by mikeharty** [comment]
A couple of minor issues I've since run into, these are in the same area, but are not directly related. Let me know if you'd like a separate ticket:

1: Argument default_value are ignored

I'm not totally clear on whether "default_value" is officially supported in the GraphQL gem, but we are using it and it does work. It appears to be left out of the implementation here: https://github.com/gmac/graphql-stitching-ruby/blob/main/lib/graphql/stitching/composer.rb#L369

I've worked around this adding a `merge_default_values` function into the monkey patch I mentioned above:

```
  def merge_default_values(type_name, members_by_location, argument_name: nil, field_name: nil)
  default_values = members_by_location.values.map(&:default_value)
  
  return nil if default_values.any?(&:nil?)
  
  if default_values.uniq.length != 1
    path = [type_name, field_name, argument_name].compact.join('.')
    raise ComposerError, "Default values for `#{path}` must be the same."
  end
  
  default_values.first
end
```

and I updated the code at the point I linked to conditionally add the default_value via kwargs if it has a value, so that it doesn't default fields to nulls that previously had no default (caused validation issues otherwise)

```
type = merge_value_types(type_name, value_types, argument_name: argument_name, field_name: field_name)
default_value = merge_default_values(type_name, arguments_by_location, argument_name: argument_name, field_name: field_name)
kwargs = {}
kwargs[:default_value] = default_value unless default_value.nil? && type.non_null?
schema_argument = owner.argument(
  argument_name,
  description: merge_descriptions(type_name, arguments_by_location, argument_name: argument_name, 
                                                                    field_name: field_name),
  deprecation_reason: merge_deprecations(type_name, arguments_by_location, argument_name: argument_name, 
                                                                           field_name: field_name),
  type: GraphQL::Stitching::Util.unwrap_non_null(type),
  required: type.non_null?,
  camelize: false,
  **kwargs
)
```

And 2: A separate but related issue one line above that code: 

```
        # Getting double args sometimes... why?
        return if owner.arguments.any? { _1.first == argument_name }
```

This line causes arguments to be dropped entirely - I haven't dug into the root of why the double args, but if I change that `return` to be `next`, my arguments stop being dropped.

I'm testing this against a reasonably substantial (~400 distinct types) schema and with these changes am generating identical schema to without stitching.

**Comment by gmac** [comment]
Hi @mikeharty – thanks for the feedback, I'm going to break apart your second post for threaded conversations

**Comment by gmac** [comment]
Focusing on the Enum conversation here – I'm having trouble following your explanation. Would you please put together a minimal example with a couple small GraphQL schemas ([something like this](https://github.com/gmac/graphql-stitching-ruby/blob/main/test/schemas/mutations.rb)) and drop that into this ticket, please? This will be a lot easier to grok with a tangible example.

**Comment by gmac** [comment]
Just circling back on this and I think I understand what you've uncovered here now... you're saying that it's possible for the same Enum key in different locations to be mapped to different internal values; so in effect:

```ruby
enum_values_by_type_location = {
  "loc1" => { "MyEnum" => { "MAGIC_VALUE" => 123 } },
  "loc2" => { "MyEnum" => { "MAGIC_VALUE" => 456 } },
}
```

So in effect we need to aggregate by enum key and then run the possible mapped values through a value merger if they don't all align. Good find.

**Comment by gmac** [comment]
Should be set in `v1.0.4`! Thanks for the detailed feedback; keep it coming if you find additional problems.
