### ISSUE TITLE
Variables with boolean value `false` are overwritten in Request.prepare!

### ISSUE THREAD

**Issue by mikeharty** [gmac/graphql-stitching-ruby#91]
In the Request class, the `prepare!` method applies default values to variables using conditional assignment:

```ruby
operation.variables.each do |v|
  @variables[v.name] ||= v.default_value
end
```

Unfortunately,`false` is falsey (obviously), so it is always overwritten with the value in `v.default_value` (which could be `nil` or `true`).

This is critical, I'd think, considering it can flip `false` boolean values to `true` if the default is `true`.

Script to reproduce (run from project root):
```ruby
require_relative 'lib/graphql/stitching'
require_relative 'lib/graphql/stitching/request'

query = <<~GRAPHQL
  query($a: Boolean, $b: Boolean, $c: Boolean = true) {
    base(a: $a, b: $b, c: $c) { id }
  }
GRAPHQL

variables = { "a" => true, "b" => false, "c" => false }
request = GraphQL::Stitching::Request.new(GraphQL.parse(query), variables: variables)
request.prepare!

puts request.variables
# {"a"=>true, "b"=>nil, "c"=>true}
```

Fix is simple, I'll open a PR in a moment with the fix + a test.

**Comment by gmac** [comment]
Good catch!

**Comment by gmac** [comment]
Resolved by https://github.com/gmac/graphql-stitching-ruby/pull/92
