### ISSUE TITLE
Remote errors are not properly propagated to clients

### ISSUE THREAD

**Issue by shyouhei** [gmac/graphql-stitching-ruby#93]
When one of our location returns an error, GraphQL::Stitching::Client doesn't propagate that error and raises `no implicit conversion of nil into Array (TypeError)` instead at this line:

https://github.com/gmac/graphql-stitching-ruby/blob/1be32f0dbd73bcaba5a4af7e7a5cdcd502298365/lib/graphql/stitching/executor/boundary_source.rb#L38

This is because that `extract_errors!(origin_sets_by_operation, errors)` is returning `nil`.

Looking at the implementation,

https://github.com/gmac/graphql-stitching-ruby/blob/1be32f0dbd73bcaba5a4af7e7a5cdcd502298365/lib/graphql/stitching/executor/boundary_source.rb#L162-L164

This `flatten!` is the crux.  It can return nil, in case the operation did not modify `errors_result`.

**Comment by gmac** [comment]
Thanks for the report, good find!

**Comment by shyouhei** [comment]
Thank you!
